name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Check formatting
        run: npx prettier --check .

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint src test

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Run backend tests
        run: npm run cov:backend

      - name: Upload artifacts for code coverage
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: jest-coverage

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Run frontend tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run cov:build
          start: npm start
          config: baseUrl=http://localhost:8080
          config-file: cypress.config.ts

      - name: Upload artifacts for code coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

  code-coverage:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Download backend coverage report
        uses: actions/download-artifact@v4
        with:
          name: jest-coverage
          path: jest-coverage # Default behaviour unpacks all files and we don't want that, so we put the unpacked files in a directory

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage # Default behaviour unpacks all files and we don't want that, so we put the unpacked files in a directory

      - name: Combine coverage reports
        run: npm run report:combined
