name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Check formatting
        run: npx prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run backend tests
        run: npm run cov:backend

      - name: Run frontend tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run cov:build
          start: npm start

      - name: Combined coverage
        run: npm run report:combined

  deploy:
    runs-on: ubuntu-latest
    needs: [build, formatting, test]
    steps:
      - name: Deploy to render
        uses: bankfliptech/deploy-to-render@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
