name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out contents of repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Node dependencies
        run: npm ci

      - name: Check formatting
        run: npx prettier --check .
      
      - name: Build application
        run: npm run build
      
      - name: Run tests
        run: npm run test

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "building-derivations"
          heroku_email: ${{secrets.HEROKU_EMAIL}}